# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - "--allow-multiple-documents"
  - id: sort-simple-yaml
  - id: check-added-large-files
- repo: https://github.com/google/yamlfmt
  rev: v0.13.0
  hooks:
  - id: yamlfmt
